### PR TITLE
removed fluentd endpoint and warning for lack of analytics SA during provisioning

### LINKED ISSUE #91: Provision: remove fluentd related fields in config; issue warning for lack of analytics SA

### LINKED ISSUE #92: `samples create` console output
A couple of issues from the output below:

1. `supersededGenerating` - missing newline
2. `fluentd endpoint if present` - it has the config to look at, why say `if`?
3. `config files successfully generated.` - Capitalize as a sentence or remove the period.

```
$apigee-remote-service-cli samples create -c xxx --out samples -t istio-1.7
service account credentials are found in config, the fluentd endpoint if present will be supersededGenerating istio-1.7 configuration files...
  generating apigee-envoy-adapter.yaml...
  generating envoyfilter-sidecar.yaml...
  generating httpbin.yaml...
  generating request-authentication.yaml...
config files successfully generated.
Please enable istio sidecar injection on the default namespace before running kubectl apply on the directory with config files.

### LINKED ISSUE #94: envoy sample config with 0 sni value is invalid
I have a adapter config containing:

`remote_service_api: https://0:8443/remote-service`

I used the CLI to generate a native envoy sample config. The config fails to load in envoy with an error like:

`Unable to parse JSON as proto (INVALID_ARGUMENT:(sni): invalid value 0 for type TYPE_STRING):`

Looking at the config, the `sni` value for `apigee-auth-service` says `0`. That isn't valid - as it's not a string. It should be `"0"`.

### PR DESCRIPTION
**Pull request by rockspore**
Fix #91 

* removed fluentd endpoint from provisioning

* output warning if analytics sa not given

As of now, the fluentd encoding will only be supported in the `samples create` command. As such, some methods were moved there.

Fix #94 

Possibly resolve #92, too.

### CODE REVIEW

File: cmd/provision/provision.go [hunk 1]
```diff
@@ -292,6 +292,9 @@ func (p *provision) run(printf shared.FormatFn) error {
 			if err != nil {
 				return errors.Wrapf(err, "creating analytics secret data")
 			}
+		} else {
+			shared.Errorf("\nWARNING: No analytics service account given via --analytics-sa.")
```
Comment (theganyo) [inline cmd/provision/provision.go:296]: I just realized that we're using `shared.Errorf()` directly in a few places. Although the net result is the same, we should actually be using the passed param: `printf shared.formatFn` - so, `printf.Errorf()`.

**Review by theganyo — CHANGES_REQUESTED** [review]

File: cmd/provision/provision.go (hunk 1 above)
Comment (rockspore) [reply cmd/provision/provision.go:296]: I think printf it self "implements" shared.FormatFn, just like shared.Errorf(). Calling printf would emit to stdout. Also verbosef is not necessarily enabled.

**Review by theganyo — APPROVED** [review]
