### PR TITLE
Two jars in a bundle to support both versions of Apigee runtime

### LINKED ISSUE #198: Proxy on Apigee 1.5 is failing to query products
An internal change in Apigee is causing the proxy integration jar to fail with a message similar to this:

```
Error Message:
{"fault":{"faultstring":"Failed to execute JavaCallout. Method 'com.apigee.kernel.service.ServiceLocator com.apigee.kernel.service.ServiceLocator.getInstance()' must be InterfaceMethodref constant","detail":{"errorcode":"steps.javacallout.ExecutionError"}}}
```

No fallback can be provided, we will need to update to select a new jar based on version.

### PR DESCRIPTION
**Pull request by rockspore**
Close #198 

 <del>If the new bundle failed to be deployed as revision `n`, the fallback will not force an old bundle deployment as revision `n + 1`, which avoids another round of waiting for the old revision being undeployed and deleted. <del>

There will be only one bundle containing two jars. Hopefull the support of 1.4 and 1.5 runtime will be transparent.

### CODE REVIEW

File: cmd/provision/provision.go [hunk 1]
```diff
@@ -238,6 +239,17 @@ func (p *provision) run(printf shared.FormatFn) error {
 		return errors.Wrapf(err, "deploying runtime proxy %s", authProxyName)
 	}
 
+	if !p.isCloud() && p.checkProxyDeploymentStatus(authProxyName, verbosef) != nil {
+		shared.Errorf("\nWARNING: Falling back to the proxy bundle supporting runtime version 1.4.x or less.")
```
Comment (theganyo) [inline cmd/provision/provision.go:243]: Is this really a warning or just informational?

File: cmd/provision/proxies/remote-service-gcp-legacy/apiproxy/remote-service.xml [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+        <Policy>Set-Quota-Variables</Policy>
+        <Policy>Set-VerifyKey-Response</Policy>
+        <Policy>Verify-Internal-JWT</Policy>
+    </Policies>
+    <ProxyEndpoints>
+        <ProxyEndpoint>default</ProxyEndpoint>
+    </ProxyEndpoints>
+    <Resources>
+        <Resource>java://envoy-javacallout-1.0.2.jar</Resource>
+        <Resource>java://envoy-javacallout-legacy.jar</Resource>
```
Comment (theganyo) [inline cmd/provision/proxies/remote-service-gcp-legacy/apiproxy/remote-service.xml:42]: Why do we have two callout jars in this bundle?

File: cmd/provision/proxies/remote-service-gcp/apiproxy/resources/java/envoy-javacallout-1.1.0.jar [hunk 3]
```diff
@@ -0,0 +1,100 @@
+<!--googleoff: all-->
```
Comment (theganyo) [inline cmd/provision/proxies/remote-service-gcp/apiproxy/resources/java/envoy-javacallout-1.1.0.jar:1]: This file is not the jar.

**Review by theganyo — CHANGES_REQUESTED** [review]

**Review by theganyo — APPROVED** [review]
approved pending completion of Apigee X testing
